version: "3"
services:

    database:
        image: postgres:10.4
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=myPassword

    s3:
        image: minio/minio
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - ./data:/data
        environment:
            MINIO_ROOT_USER: root_user
            MINIO_ROOT_PASSWORD: root_password
        command: minio server /data --console-address ":9001"

    data_service:
        build: .
        ports:
            - "8000:5000"
